server:  
  port: 8761
  
eureka:
  client:
    register-with-eureka: false #al iniciar no se registra
    fetch-registry: false  #al iniciar no carga los registros
  server:
    wait-time-in-ms-when-sync-empty: 5
  serviceUrl:
    defaultZone: http://localhost:8761
    

    