server:
  port: 8080
  
watson:
  authentication:
    url: https://gateway.watsonplatform.net/assistant/api
    username: 7ec74014-003a-4fbe-a3e0-06c69a591705
    password: 0ULqNwXHd2Sb
  workspace1:
    name: b4666c9c-b6dd-41c9-9c67-513d61f12a6b
    
security:
  basic:
    enabled: false