watson:
  authentication:
    url: https://gateway.watsonplatform.net/assistant/api
    username: 97988ae8-6239-4624-9810-12f202583e89
    password: qsQmauKnqlRV
    
  workspace1:
    name: afcb9ab7-e4c4-4352-a7e7-7d8d4b7854e8