security:
 oauth2:
  resource:
    userInfoUri: http://localhost:8901/user
  basic:
    enabled: false
    
signing:
  key: 345345fsdgsf5345
  
#slf4j level config
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.itemsharing: DEBUG
    

      
      